// Code generated by "go run tools/ast/main.go"; DO NOT EDIT.

package main

type Expr any

type Binary struct {
	Left     Expr
	Operator Token
	Right    Expr
}

type Grouping struct {
	Expression Expr
}

type Literal struct {
	Object any
}

type Unary struct {
	Operator Token
	Right    Expr
}
