// Code generated by "stringer --type TokenType --output=./token_type_stringer.gen.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[leftParen-0]
	_ = x[rightParen-1]
	_ = x[leftBrace-2]
	_ = x[rightBrace-3]
	_ = x[comma-4]
	_ = x[dot-5]
	_ = x[minus-6]
	_ = x[plus-7]
	_ = x[semicolon-8]
	_ = x[slash-9]
	_ = x[star-10]
	_ = x[bang-11]
	_ = x[bangEqual-12]
	_ = x[equal-13]
	_ = x[equalEqual-14]
	_ = x[greater-15]
	_ = x[greaterEqual-16]
	_ = x[less-17]
	_ = x[lessEqual-18]
	_ = x[identifier-19]
	_ = x[stringw-20]
	_ = x[number-21]
	_ = x[and-22]
	_ = x[class-23]
	_ = x[elsew-24]
	_ = x[falsew-25]
	_ = x[fun-26]
	_ = x[forw-27]
	_ = x[ifw-28]
	_ = x[nilw-29]
	_ = x[or-30]
	_ = x[printw-31]
	_ = x[returnw-32]
	_ = x[super-33]
	_ = x[this-34]
	_ = x[truew-35]
	_ = x[varw-36]
	_ = x[while-37]
	_ = x[eof-38]
}

const _TokenType_name = "leftParenrightParenleftBracerightBracecommadotminusplussemicolonslashstarbangbangEqualequalequalEqualgreatergreaterEquallesslessEqualidentifierstringwnumberandclasselsewfalsewfunforwifwnilworprintwreturnwsuperthistruewvarwwhileeof"

var _TokenType_index = [...]uint8{0, 9, 19, 28, 38, 43, 46, 51, 55, 64, 69, 73, 77, 86, 91, 101, 108, 120, 124, 133, 143, 150, 156, 159, 164, 169, 175, 178, 182, 185, 189, 191, 197, 204, 209, 213, 218, 222, 227, 230}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
